import { useRef, useEffect } from 'react'
import Head from 'next/head'
import {
  Button,
  Input,
  Checkbox,
  Switch,
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionPanel,
  AccordionIcon,
} from '@chakra-ui/react'

export default function Home() {
  const elRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    console.log('elRef: ', elRef.current)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <div className="flex flex-col gap-8 max-w-5xl px-6 py-16 mx-auto">
          <Input />
          <Checkbox>Checkbox</Checkbox>
          <Switch id="test" />
          <Button colorScheme="teal">Button</Button>
          <Accordion
            ref={elRef}
            allowMultiple
          >
            <AccordionItem>
              <AccordionButton>Accordion 1</AccordionButton>
              <AccordionPanel>Accordion Panel 1</AccordionPanel>
            </AccordionItem>
            <AccordionItem>
              <AccordionButton>Accordion 2</AccordionButton>
              <AccordionPanel>Accordion Panel 2</AccordionPanel>
            </AccordionItem>
            <AccordionItem>
              <AccordionButton>Accordion 3</AccordionButton>
              <AccordionPanel>Accordion Panel 3</AccordionPanel>
            </AccordionItem>
          </Accordion>
        </div>
      </main>
    </>
  )
}
